// Generated by CoffeeScript 1.4.0
var code, definition, errors, path, _fn;

path = require('path');

errors = require(path.join(process.cwd(), 'definitions', 'errors.json'));

exports.outputFor = function(code) {
  return {
    error: {
      message: errors[code].message,
      code: code
    }
  };
};

_fn = function() {
  var _code, _definition;
  _code = code;
  _definition = definition;
  return exports[_code] = function(res, debug_data) {
    var output;
    res.statusCode = _definition.http_status;
    if (res.app.settings.env !== 'test') {
      console.log(("ERROR " + _definition.http_status + ": " + _code + " - " + _definition.message).error);
    }
    output = {
      error: {
        message: _definition.message,
        code: _code
      }
    };
    if (debug_data && res.app.settings.env === 'development') {
      output.debug = debug_data;
    }
    return res.json(output);
  };
};
for (code in errors) {
  definition = errors[code];
  _fn();
}
